dapricot/blog/urls.py
from django.urls import path

from dapricot.blog import views

app_name = 'dablog'

urlpatterns = [
    path('', views.postList, name='main_list'),
    path('p<int:page>', views.postList, name='main_list'),
    
    path('<int:year>', views.datePostList, name='date_filter_posts'),
    path('<int:year>/', views.datePostList, name='date_filter_posts'),
    path('<int:year>/p<int:page>', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>/', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>/p<int:page>', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>/<int:day>', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>/<int:day>/', views.datePostList, name='date_filter_posts'),
    path('<int:year>/<int:month>/<int:day>/p<int:page>', views.datePostList, name='date_filter_posts'),
    
    path('<int:year>/<int:month>/<int:day>/<slug:slug>', views.post, name='post'),
    
    path('<slug:filter_name>/', views.filterList, name='filter_list'),
    path('<slug:filter_name>/p<int:page>', views.filterList, name='filter_list'),
    
    path('<slug:filter_name>/<slug:value>/', views.postList, name='filter_posts'),
    path('<slug:filter_name>/<slug:value>/p<int:page>', views.postList, name='filter_posts'),
    
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
]

dapricot/blog/templates/dapricot/blog/fragments/pages_list.html
<article class="paginator">
	<section class="full">
{% for p in post_list.paginator.page_range %}
	{% if p == post_list.number %}
<span>{{p}}</span>
	{% elif filter.0 %}
<a href="{% url 'dablog:filter_posts' filter_name=filter.0 value=filter.1.slug page=p %}">{{p}}</a>
	{% else %}
<a href="{% url 'dablog:main_list' page=p %}">{{p}}</a>
	{% endif %}
{% endfor%}
	</section>
</article>

dapricot/blog/templates/dapricot/blog/fragments/post_full.html
{% load static %}
<article class="title">
	<h1>{{ post.title }}</h1>
	<h4>{{ post.publication_date.date }}</h4>
</article>
<article class="post">
	<section>
	{{ post.content | safe }}
	</section>
	<aside class="author">
		{% if post.author.avatar %}
		<img src="{{ post.author.avatar }}" alt="author_avatar"/>
		{% else %}
		<img src="{% static 'img/avatar-default.png' %}" alt="author_avatar"/>
		{% endif %}
		<div>By {{ post.author.get_full_name }}</div>
	</aside> 
	<aside>
		<b>Category:</b><a href="{%url 'dablog:filter_posts' filter_name='category' value=post.category.slug %}" class="category">{{ post.category }}</a>
		<hr />
		<b>Tags:</b>		
		{% for tag in post.tags.all %}
			<a href="{%url 'dablog:filter_posts' filter_name='tag' value=tag.slug %}" class="tag">{{ tag }}</a>
		{% endfor %}
	</aside>
	<aside>{% include 'dapricot/blog/fragments/share_links.html'%}s</aside>
</article>
{% if post.enable_comments %}
<article class="title">
	<h2>Comentarios:</h2>
	<h4>Tu correo es necesario para evitar spam, este jamás se mostrará a terceros.</h4>
	<h4>Se enviará correo únicamente para validar que eres dueño del mismo.</h4>
	<h4>Los comentarios aparecerán en la página en cuanto sean aprobados por el administrador</h4>
</article>
<article class="comments">
	<aside>
		<form method="post" >
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="button">Enviar comentario</button>
		</form>
	</aside>
	<section>
	{% for comment in comments %}
		{% if comment.status == 'a' %}
		<p><b>{{ comment.author.nickname }}</b> | <i>el {{ comment.creation_date|date:"SHORT_DATE_FORMAT" }} a las {{ comment.creation_date|time:"H:i" }}</i>
		<p>{{ comment.content }}</p>
		<hr/>
		{% endif %}
	{% endfor %}
	</section>
</article>
{% endif %}

dapricot/blog/templates/dapricot/blog/fragments/post_preview.html
<article>
	<section>
	<a href="{%url 'dablog:post' day=post.publication_date.day month=post.publication_date.month year=post.publication_date.year slug=post.slug %}"><h4>{{ post.title }}</h4></a>
	<p>
	{{ post.get_preview }} (...)
	</p>
	</section>
	<aside>
		<h6 class="icon-calendar"> {{ post.publication_date.date }}</h6>
		<hr />

		<h6 class="icon-list">
		{% if filter.0 == 'category' %}
		Tags:
		{% for tag in post.tags.all %}
		<a href="{% url 'dablog:filter_posts' filter_name='tag' value=tag.slug %}">{{ tag.name }}</a>,
		{% endfor %}
		{% elif filter.0 == 'tag' %}
		Categoria:
		<a href="{% url 'dablog:filter_posts' filter_name='category' value=post.category.slug %}">{{ post.category }}</a>
		{% else %}
		Categoria:
		<a href="{% url 'dablog:filter_posts' filter_name='category' value=post.category.slug %}">{{ post.category }}</a>
		</h6>
		<hr/>
		<h6 class="icon-list">
		Tags:
		{% for tag in post.tags.all %}
		<a href="{% url 'dablog:filter_posts' filter_name='tag' value=tag.slug %}">{{ tag.name }}</a>,
		{% endfor %}
		{% endif %}
		</h6>
		
	</aside>
</article>

dapricot/blog/templates/dapricot/blog/fragments/share_links.html
{% url 'dablog:post' day=post.publication_date.day month=post.publication_date.month year=post.publication_date.year slug=post.slug as p_url%}

{% with p_permalink=request.scheme|add:"://"|add:request.get_host|add:p_url %}
<h4>Compartir:</h4>
<hr/>
<ul class="menu-horizontal">
<li><a href="https://www.facebook.com/sharer.php?u={{ p_permalink }}" class="button-secondary icon-facebook"></a></li>
<li><a href="https://twitter.com/intent/tweet?url={{ p_permalink }}&text={{ post.title }}&hashtags=orishikudotcom" class="button-secondary icon-twitter"></a></li>
<li><a href="http://pinterest.com/pin/create/link/?url={{ p_permalink }}" class="button-secondary icon-pinterest"></a></li>
<li><a href="https://www.linkedin.com/shareArticle?mini=true&url={{ p_permalink }}&title={{ post.title }}&summary={{ post.get_preview }}" class="button-secondary icon-linkedin"></a></li>
</ul>
{% endwith %}